services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graduance_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: container-registry.oracle.com/mysql/community-server:latest
    container_name: graduance_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: graduance
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
